#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x447BF683AA3B26C3 (certbot-team@eff.org)
#
Name     : pypi-certbot_dns_google
Version  : 1.29.0
Release  : 9
URL      : https://files.pythonhosted.org/packages/e8/2c/2522d085432558676994441b007a84c0bb531e0805f10a5130fc1adb0cdd/certbot-dns-google-1.29.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/e8/2c/2522d085432558676994441b007a84c0bb531e0805f10a5130fc1adb0cdd/certbot-dns-google-1.29.0.tar.gz
Source1  : https://files.pythonhosted.org/packages/e8/2c/2522d085432558676994441b007a84c0bb531e0805f10a5130fc1adb0cdd/certbot-dns-google-1.29.0.tar.gz.asc
Summary  : Google Cloud DNS Authenticator plugin for Certbot
Group    : Development/Tools
License  : Apache-2.0
Requires: pypi-certbot_dns_google-license = %{version}-%{release}
Requires: pypi-certbot_dns_google-python = %{version}-%{release}
Requires: pypi-certbot_dns_google-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(acme)
BuildRequires : pypi(certbot)
BuildRequires : pypi(google_api_python_client)
BuildRequires : pypi(httplib2)
BuildRequires : pypi(oauth2client)
BuildRequires : pypi(setuptools)

%description
Google Cloud DNS Authenticator plugin for Certbot

%package license
Summary: license components for the pypi-certbot_dns_google package.
Group: Default

%description license
license components for the pypi-certbot_dns_google package.


%package python
Summary: python components for the pypi-certbot_dns_google package.
Group: Default
Requires: pypi-certbot_dns_google-python3 = %{version}-%{release}

%description python
python components for the pypi-certbot_dns_google package.


%package python3
Summary: python3 components for the pypi-certbot_dns_google package.
Group: Default
Requires: python3-core
Provides: pypi(certbot_dns_google)
Requires: pypi(acme)
Requires: pypi(certbot)
Requires: pypi(google_api_python_client)
Requires: pypi(httplib2)
Requires: pypi(oauth2client)
Requires: pypi(setuptools)

%description python3
python3 components for the pypi-certbot_dns_google package.


%prep
%setup -q -n certbot-dns-google-1.29.0
cd %{_builddir}/certbot-dns-google-1.29.0
pushd ..
cp -a certbot-dns-google-1.29.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1657150058
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 setup.py build

popd
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-certbot_dns_google
cp %{_builddir}/certbot-dns-google-1.29.0/LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-certbot_dns_google/d095fa0d394cc9417a65aecd0d28e7d10e762f98
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -tt setup.py build install --root=%{buildroot}-v3
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-certbot_dns_google/d095fa0d394cc9417a65aecd0d28e7d10e762f98

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
